- name: goalnetstanchioncolor2g
  order: 0
  type: int
  range:
    min: 0
    max: 255
  default: 0
- name: goalnetstanchioncolor2r
  order: 1
  type: int
  range:
    min: 0
    max: 255
  default: 0
- name: goalnetstanchioncolor1b
  order: 2
  type: int
  range:
    min: 0
    max: 255
  default: 0
- name: goalnetstanchioncolor2b
  order: 3
  type: int
  range:
    min: 0
    max: 255
  default: 0
- name: goalnetstanchioncolor1r
  order: 4
  type: int
  range:
    min: 0
    max: 255
  default: 0
- name: name
  order: 5
  type: string
  default: ''
- name: goalnetstanchioncolor1g
  order: 6
  type: int
  range:
    min: 0
    max: 255
  default: 0
- name: timeofday3
  order: 7
  type: int
  range:
    min: 0
    max: 5
  default: 5
- name: adboardsidelinedistance
  order: 8
  type: int
  range:
    min: 0
    max: 999999
  default: 400
- name: stadiumgloalnetdepth
  order: 9
  type: int
  range:
    min: 0
    max: 999999
  default: 229
- name: hometeamid
  order: 10
  type: int
  range:
    min: 0
    max: 200000
  default: 0
- name: presassetfour
  order: 11
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: presassetone
  order: 12
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: issmallsided
  order: 13
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: supportsgoalnetshape
  order: 14
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: dronetype
  order: 15
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: capacity
  order: 16
  type: int
  range:
    min: 0
    max: 200000
  default: 10000
- name: hasintrosnownightvideo
  order: 17
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: seatcolor
  order: 18
  type: int
  range:
    min: 1
    max: 8
  default: 1
- name: sectionfacedbydefault
  order: 19
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: stadhometechzonemaxz
  order: 20
  type: int
  range:
    min: -65536
    max: 65535
  default: -3600
- name: hasunofficialname
  order: 21
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: pitchcolor
  order: 22
  type: int
  range:
    min: 0
    max: 10
  default: 0
- name: policetypecode
  order: 23
  type: int
  range:
    min: 0
    max: 15
  default: 1
- name: timeofday4
  order: 24
  type: int
  range:
    min: 0
    max: 5
  default: 5
- name: pitchwear
  order: 25
  type: int
  range:
    min: 0
    max: 10
  default: 0
- name: stadawaytechzonemaxx
  order: 26
  type: int
  range:
    min: -65536
    max: 65535
  default: 500
- name: stadiumpitchlength
  order: 27
  type: int
  range:
    min: 0
    max: 999999
  default: 10500
- name: hasintrorainnightvideo
  order: 28
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: stadiumgoalnetstyle
  order: 29
  type: int
  range:
    min: 0
    max: 50
  default: 0
- name: gmavailability
  order: 30
  type: int
  range:
    min: 0
    max: 3
  default: 1
- name: cityid
  order: 31
  type: int
  range:
    min: 0
    max: 1023
  default: 0
- name: playsurfacetype
  order: 32
  type: int
  range:
    min: 0
    max: 7
  default: 0
- name: pitchtarps
  order: 33
  type: int
  range:
    min: 0
    max: 2
  default: 0
- name: upgradetier
  order: 34
  type: int
  range:
    min: 0
    max: 8
  default: 0
- name: tod4weather
  order: 35
  type: int
  range:
    min: 0
    max: 3
  default: 0
- name: countrycode
  order: 36
  type: int
  range:
    min: 0
    max: 3000
  default: 0
- name: stadiummowpattern_code
  order: 37
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: stadhometechzonemaxx
  order: 38
  type: int
  range:
    min: -65536
    max: 65535
  default: 0
- name: colorregion
  order: 39
  type: int
  range:
    min: 0
    max: 31
  default: 0
- name: defaultseason
  order: 40
  type: int
  range:
    min: 0
    max: 3
  default: 1
- name: stadiumid
  order: 41
  type: int
  range:
    min: 0
    max: 2000
  default: 0
  unique: true
- name: tunnellocation
  order: 42
  type: int
  range:
    min: 0
    max: 2
  default: 0
- name: cameraheight
  order: 43
  type: int
  range:
    min: 0
    max: 31
  default: 15
- name: stadiumgoalpoststyle
  order: 44
  type: int
  range:
    min: 0
    max: 7
  default: 0
- name: hasintrodrydayvideo
  order: 45
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: stadawaytechzoneminz
  order: 46
  type: int
  range:
    min: -65536
    max: 65535
  default: -3600
- name: hasmexicanwave
  order: 47
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: hascenteradboard
  order: 48
  type: int
  range:
    min: 0
    max: 1
  default: 1
- name: defaulttime
  order: 49
  type: int
  range:
    min: 1000
    max: 2345
  default: 2000
- name: isstadiumavailable
  order: 50
  type: int
  range:
    min: 0
    max: 1
  default: 1
- name: stadhometechzoneminx
  order: 51
  type: int
  range:
    min: -65536
    max: 65535
  default: 0
- name: ismirrored
  order: 52
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: stadiumgoalnettype
  order: 53
  type: int
  range:
    min: 0
    max: 3
  default: 0
- name: stadiumpitchwidth
  order: 54
  type: int
  range:
    min: 0
    max: 999999
  default: 6800
- name: replay360degree
  order: 55
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: stadhometechzoneminz
  order: 56
  type: int
  range:
    min: -65536
    max: 65535
  default: 0
- name: inflatables
  order: 57
  type: int
  range:
    min: 0
    max: 8191
  default: 0
- name: stadiumtype
  order: 58
  type: int
  range:
    min: 0
    max: 3
  default: 0
- name: islicensed
  order: 59
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: tifo
  order: 60
  type: int
  range:
    min: 0
    max: 4
  default: 0
- name: hasintroraindayvideo
  order: 61
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: stadiumgoalnetpattern
  order: 62
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: stadawaytechzonemaxz
  order: 63
  type: int
  range:
    min: -65536
    max: 65535
  default: 0
- name: stadiumgoalnettension
  order: 64
  type: int
  range:
    min: 0
    max: 2
  default: 0
- name: hasintrodrynightvideo
  order: 65
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: tod1weather
  order: 66
  type: int
  range:
    min: 0
    max: 3
  default: 3
- name: dlc
  order: 67
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: tod2weather
  order: 68
  type: int
  range:
    min: 0
    max: 3
  default: 3
- name: adboardtype
  order: 69
  type: int
  range:
    min: 0
    max: 3
  default: 0
- name: rotation360degree
  order: 70
  type: int
  range:
    min: 0
    max: 360
  default: 0
- name: camerazoom
  order: 71
  type: int
  range:
    min: 0
    max: 15
  default: 9
- name: languageregion
  order: 72
  type: int
  range:
    min: 0
    max: 25
  default: 1
- name: adboardendlinedistance
  order: 73
  type: int
  range:
    min: 0
    max: 999999
  default: 500
- name: presassetthree
  order: 74
  type: int
  range:
    min: 0
    max: 2
  default: 2
- name: iseditable
  order: 75
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: isdynamic
  order: 76
  type: int
  range:
    min: 0
    max: 1
  default: 1
- name: tod3weather
  order: 77
  type: int
  range:
    min: 0
    max: 3
  default: 0
- name: frontsettype
  order: 78
  type: int
  range:
    min: 0
    max: 2
  default: 0
- name: hasintrosnowdayvideo
  order: 79
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: upgradestyle
  order: 80
  type: int
  range:
    min: 0
    max: 5
  default: 0
- name: defaultweather
  order: 81
  type: int
  range:
    min: 0
    max: 8
  default: 0
- name: genericrank
  order: 82
  type: int
  range:
    min: -1
    max: 10
  default: -1
- name: timeofday1
  order: 83
  type: int
  range:
    min: 0
    max: 5
  default: 1
- name: supportsunlicensedbanners
  order: 84
  type: int
  range:
    min: 0
    max: 1
  default: 1
- name: timeofday2
  order: 85
  type: int
  range:
    min: 0
    max: 5
  default: 3
- name: supportsunlicensedtifos
  order: 86
  type: int
  range:
    min: 0
    max: 1
  default: 1
- name: pitchlinecolor
  order: 87
  type: int
  range:
    min: 0
    max: 10
  default: 0
- name: stadawaytechzoneminx
  order: 88
  type: int
  range:
    min: -65536
    max: 65535
  default: 400
- name: hasintrovideo
  order: 89
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: goalnetads
  order: 90
  type: int
  range:
    min: 0
    max: 1
  default: 0
