- name: firstname
  order: 0
  type: string
  default: ''
- name: surname
  order: 1
  type: string
  default: ''
- name: teamid
  order: 2
  type: int
  range:
    min: 0
    max: 200000
  default: 0
