import { fifaTableConfig } from './config';
import { Fifa, FifaConfig, Table } from './interfaces';

export const fifaConfig = (fifa: Fifa): FifaConfig => {
  const config = new FifaConfig();
  config.competition = fifaTableConfig(fifa, Table.Competition);
  config.dcplayernames = fifaTableConfig(fifa, Table.DcPlayerNames);
  config.formations = fifaTableConfig(fifa, Table.Formations);
  config.leaguerefereelinks = fifaTableConfig(fifa, Table.LeagueRefereeLinks);
  config.leagues = fifaTableConfig(fifa, Table.Leagues);
  config.leagueteamlinks = fifaTableConfig(fifa, Table.LeagueTeamLinks);
  config.manager = fifaTableConfig(fifa, Table.Manager);
  config.nations = fifaTableConfig(fifa, Table.Nations);
  config.player_grudgelove = fifaTableConfig(fifa, Table.PlayerGrudgelove);
  config.playerboots = fifaTableConfig(fifa, Table.PlayerBoots);
  config.playerloans = fifaTableConfig(fifa, Table.PlayerLoans);
  config.playernames = fifaTableConfig(fifa, Table.PlayerNames);
  config.players = fifaTableConfig(fifa, Table.Players);
  config.previousteam = fifaTableConfig(fifa, Table.PreviousTeam);
  config.referee = fifaTableConfig(fifa, Table.Referee);
  config.rivals = fifaTableConfig(fifa, Table.Rivals);
  config.rowteamnationlinks = fifaTableConfig(fifa, Table.RowTeamNationLinks);
  config.shoecolors = fifaTableConfig(fifa, Table.ShoeColors);
  config.stadiums = fifaTableConfig(fifa, Table.Stadiums);
  config.teamballs = fifaTableConfig(fifa, Table.TeamBalls);
  config.teamkits = fifaTableConfig(fifa, Table.TeamKits);
  config.teamnationlinks = fifaTableConfig(fifa, Table.TeamNationLinks);
  config.teamplayerlinks = fifaTableConfig(fifa, Table.TeamPlayerLinks);
  config.teams = fifaTableConfig(fifa, Table.Teams);
  config.teamstadiumlinks = fifaTableConfig(fifa, Table.TeamStadiumLinks);
  return config;
};
