- name: competitioncolor1g
  order: 0
  type: int
  range:
    min: 0
    max: 255
  default: 0
- name: badge_ls
  order: 1
  type: int
  range:
    min: -1
    max: 9999999
  default: -1
- name: competitionid
  order: 2
  type: int
  range:
    min: 0
    max: 9999999
  default: 1
- name: competitioncolor2r
  order: 3
  type: int
  range:
    min: 0
    max: 255
  default: 0
- name: competitioncolor2g
  order: 4
  type: int
  range:
    min: 0
    max: 255
  default: 0
- name: competitioncolor1b
  order: 5
  type: int
  range:
    min: 0
    max: 255
  default: 0
- name: badge_rs
  order: 6
  type: int
  range:
    min: -1
    max: 9999999
  default: -1
- name: competitioncolor1r
  order: 7
  type: int
  range:
    min: 0
    max: 255
  default: 0
- name: competitioncolor2b
  order: 8
  type: int
  range:
    min: 0
    max: 255
  default: 0
- name: badge_chest_champions
  order: 9
  type: int
  range:
    min: -1
    max: 9999999
  default: -1
- name: badge_ls_champions
  order: 10
  type: int
  range:
    min: -1
    max: 9999999
  default: -1
- name: armband_type_1
  order: 11
  type: int
  range:
    min: -1
    max: 9999999
  default: -1
- name: badge_chest
  order: 12
  type: int
  range:
    min: -1
    max: 9999999
  default: -1
- name: badge_rs_champions
  order: 13
  type: int
  range:
    min: -1
    max: 9999999
  default: -1
- name: armband_type_0
  order: 14
  type: int
  range:
    min: -1
    max: 9999999
  default: -1
- name: goalscoringrecord
  order: 15
  type: int
  range:
    min: 0
    max: 200
  default: 0
- name: hasmediarope
  order: 16
  type: int
  range:
    min: 0
    max: 2
  default: 0
- name: celebrationmediapen
  order: 17
  type: int
  range:
    min: 0
    max: 1
  default: 1
- name: isteampitchflagenabledstage
  order: 18
  type: int
  range:
    min: 0
    max: 15
  default: 9
- name: isstanchionflamethrowerenabledstage
  order: 19
  type: int
  range:
    min: 0
    max: 15
  default: 9
- name: celebrationsponsorboard
  order: 20
  type: int
  range:
    min: 0
    max: 2
  default: 1
- name: winterballid
  order: 21
  type: int
  range:
    min: -1
    max: 300
  default: -1
- name: goaljingle
  order: 22
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: isstadiumdressingenabledstage
  order: 23
  type: int
  range:
    min: 0
    max: 15
  default: 9
- name: isgoallinetechcompenabledstage
  order: 24
  type: int
  range:
    min: 0
    max: 15
  default: 9
- name: abbapenalties
  order: 25
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: hasvikingclap
  order: 26
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: competitionimportance
  order: 27
  type: int
  range:
    min: 0
    max: 15
  default: 1
- name: finalballid
  order: 28
  type: int
  range:
    min: -1
    max: 300
  default: -1
- name: presassettwo
  order: 29
  type: int
  range:
    min: 0
    max: 2
  default: 0
- name: adboardplacement
  order: 30
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: iscompetitionscarfenabled
  order: 31
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: authentictarpadboardb
  order: 32
  type: int
  range:
    min: 0
    max: 16
  default: 0
- name: introanthemidle
  order: 33
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: isbannerenabled
  order: 34
  type: int
  range:
    min: 0
    max: 1
  default: 1
- name: pitchtarps
  order: 35
  type: int
  range:
    min: 0
    max: 5
  default: 0
- name: ischampionboardenabled
  order: 36
  type: int
  range:
    min: 0
    max: 2
  default: 0
- name: introconfetti
  order: 37
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: colorregion
  order: 38
  type: int
  range:
    min: 0
    max: 31
  default: 1
- name: isuniqueadboardscompenabled
  order: 39
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: ishandshakeboardenabled
  order: 40
  type: int
  range:
    min: 0
    max: 3
  default: 0
- name: country_lock
  order: 41
  type: int
  range:
    min: -1
    max: 3000
  default: -1
- name: isballplinthenabledstage
  order: 42
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: hasstandingcrowd
  order: 43
  type: int
  range:
    min: 0
    max: 1
  default: 1
- name: iscompetitionpoleflagenabled
  order: 44
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: isteampitchflagenabled
  order: 45
  type: int
  range:
    min: 0
    max: 15
  default: 9
- name: isflamethrowercannonsenabled
  order: 46
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: hasmascot
  order: 47
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: iscenterpitchflagenabledstage
  order: 48
  type: int
  range:
    min: 0
    max: 15
  default: 9
- name: iscompetitioncrowdcardsenabled
  order: 49
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: player_display_pts
  order: 50
  type: int
  range:
    min: 0
    max: 3
  default: 0
- name: isarchwayenabled
  order: 51
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: isgoallinetechcompenabled
  order: 52
  type: int
  range:
    min: 0
    max: 15
  default: 9
- name: authenticwipe
  order: 53
  type: int
  range:
    min: 0
    max: 3
  default: 1
- name: replay360degree
  order: 54
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: isuniquetrophypedestalenabled
  order: 55
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: custombibs
  order: 56
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: isinjuryboardenabled
  order: 57
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: isintroconfettienabledstage
  order: 58
  type: int
  range:
    min: 0
    max: 15
  default: 9
- name: inflatables
  order: 59
  type: int
  range:
    min: 0
    max: 8191
  default: 0
- name: player_display_ptw_tr
  order: 60
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: isstadiumdressingunique
  order: 61
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: isvanishingsprayhomeenabled
  order: 62
  type: int
  range:
    min: 0
    max: 15
  default: 1
- name: isflamethrowercannonsenabledstage
  order: 63
  type: int
  range:
    min: 0
    max: 15
  default: 9
- name: hasauthentictarpads
  order: 64
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: isvanishingsprayenabled
  order: 65
  type: int
  range:
    min: 0
    max: 15
  default: 1
- name: stanchionflamethrower
  order: 66
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: has_var
  order: 67
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: languageregion
  order: 68
  type: int
  range:
    min: 1
    max: 25
  default: 1
- name: ispitchtarpsenabledstage
  order: 69
  type: int
  range:
    min: 0
    max: 15
  default: 9
- name: celebrationbackboard
  order: 70
  type: int
  range:
    min: 0
    max: 2
  default: 0
- name: adboardplacementstage
  order: 71
  type: int
  range:
    min: 0
    max: 15
  default: 9
- name: isstadiumdressinguniquestage
  order: 72
  type: int
  range:
    min: 0
    max: 15
  default: 9
- name: iscenterpitchflagenabled
  order: 73
  type: int
  range:
    min: 0
    max: 15
  default: 9
- name: crowdregion
  order: 74
  type: int
  range:
    min: 0
    max: 31
  default: 0
- name: pitchbranding
  order: 75
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: isgoallinetechhomeleagueenabled
  order: 76
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: stadiumcrowdmap
  order: 77
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: ballid
  order: 78
  type: int
  range:
    min: 0
    max: 300
  default: 0
- name: celebrationstage
  order: 79
  type: int
  range:
    min: 0
    max: 2
  default: 1
- name: authentictarpadboarda
  order: 80
  type: int
  range:
    min: 0
    max: 16
  default: 0
- name: celebrationarchedboard
  order: 81
  type: int
  range:
    min: 0
    max: 2
  default: 0
- name: isballplinthenabled
  order: 82
  type: int
  range:
    min: 0
    max: 15
  default: 0
- name: introteamportrait
  order: 83
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: onpitchgraphics
  order: 84
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: crowdskintonecode
  order: 85
  type: int
  range:
    min: 0
    max: 15
  default: 2
- name: competitionchampionid
  order: 86
  type: int
  range:
    min: -1
    max: 200000
  default: -1
- name: haslargeflag
  order: 87
  type: int
  range:
    min: 0
    max: 1
  default: 0
- name: isarchwayenabledstage
  order: 88
  type: int
  range:
    min: 0
    max: 15
  default: 9
- name: isgoalnetadsenabledstage
  order: 89
  type: int
  range:
    min: 0
    max: 15
  default: 9
- name: isstadiumdressingenabled
  order: 90
  type: int
  range:
    min: 0
    max: 15
  default: 9
- name: goalnetads
  order: 91
  type: int
  range:
    min: 0
    max: 1
  default: 0
